export default{
  "login": "MohamedAbdelRazek222",
  "id": 118555438,
  "node_id": "U_kgDOBxEDLg",
  "avatar_url": "https://avatars.githubusercontent.com/u/118555438?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/MohamedAbdelRazek222",
  "html_url": "https://github.com/MohamedAbdelRazek222",
  "followers_url": "https://api.github.com/users/MohamedAbdelRazek222/followers",
  "following_url": "https://api.github.com/users/MohamedAbdelRazek222/following{/other_user}",
  "gists_url": "https://api.github.com/users/MohamedAbdelRazek222/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/MohamedAbdelRazek222/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/MohamedAbdelRazek222/subscriptions",
  "organizations_url": "https://api.github.com/users/MohamedAbdelRazek222/orgs",
  "repos_url": "https://api.github.com/users/MohamedAbdelRazek222/repos",
  "events_url": "https://api.github.com/users/MohamedAbdelRazek222/events{/privacy}",
  "received_events_url": "https://api.github.com/users/MohamedAbdelRazek222/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Mohamed Abdelrazek",
  "company": "Back end Developer",
  "blog": "linkedin.com/in/mohamed-abdelrazek22",
  "location": "cairo",
  "email": null,
  "hireable": null,
  "bio": "I am a Mearn Stack developer. I have a knowledge in html,css ,Sass,JavaScript ,TypeScript ,React and Angular in FrontEnd and Node.js ,express and MongoDb in Bac",
  "twitter_username": null,
  "public_repos": 10,
  "public_gists": 0,
  "followers": 2,
  "following": 4,
  "created_at": "2022-11-18T16:39:00Z",
  "updated_at": "2023-02-14T05:28:43Z"
  }