export default[
  {
  "login": "AhmedAliAbdAlMowla",
  "id": 47031477,
  "node_id": "MDQ6VXNlcjQ3MDMxNDc3",
  "avatar_url": "https://avatars.githubusercontent.com/u/47031477?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/AhmedAliAbdAlMowla",
  "html_url": "https://github.com/AhmedAliAbdAlMowla",
  "followers_url": "https://api.github.com/users/AhmedAliAbdAlMowla/followers",
  "following_url": "https://api.github.com/users/AhmedAliAbdAlMowla/following{/other_user}",
  "gists_url": "https://api.github.com/users/AhmedAliAbdAlMowla/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/AhmedAliAbdAlMowla/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/AhmedAliAbdAlMowla/subscriptions",
  "organizations_url": "https://api.github.com/users/AhmedAliAbdAlMowla/orgs",
  "repos_url": "https://api.github.com/users/AhmedAliAbdAlMowla/repos",
  "events_url": "https://api.github.com/users/AhmedAliAbdAlMowla/events{/privacy}",
  "received_events_url": "https://api.github.com/users/AhmedAliAbdAlMowla/received_events",
  "type": "User",
  "site_admin": false
  },
  {
  "login": "MohamedAbdelrazek22",
  "id": 98935705,
  "node_id": "U_kgDOBeWjmQ",
  "avatar_url": "https://avatars.githubusercontent.com/u/98935705?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/MohamedAbdelrazek22",
  "html_url": "https://github.com/MohamedAbdelrazek22",
  "followers_url": "https://api.github.com/users/MohamedAbdelrazek22/followers",
  "following_url": "https://api.github.com/users/MohamedAbdelrazek22/following{/other_user}",
  "gists_url": "https://api.github.com/users/MohamedAbdelrazek22/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/MohamedAbdelrazek22/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/MohamedAbdelrazek22/subscriptions",
  "organizations_url": "https://api.github.com/users/MohamedAbdelrazek22/orgs",
  "repos_url": "https://api.github.com/users/MohamedAbdelrazek22/repos",
  "events_url": "https://api.github.com/users/MohamedAbdelrazek22/events{/privacy}",
  "received_events_url": "https://api.github.com/users/MohamedAbdelrazek22/received_events",
  "type": "User",
  "site_admin": false
  }
  ]